### ISSUE TITLE
Mac install Error

### ISSUE THREAD

**Issue by simingli** [go-delve/homebrew-delve#7]
# ali @ alideMacBook-Pro in ~ on git:master x [14:33:53] C:1
$ brew install go-delve/delve/delve
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing delve from go-delve/homebrew-delve
==> Installing dependencies for go-delve/delve/delve: go
==> Installing go-delve/delve/delve dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.5.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/go-1.5.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
==> ./make.bash --no-clean
runtime.main()
	/private/tmp/go20170301-19561-2mto9i/go/gobootstrap/src/runtime/proc.go:63 +0xf3 fp=0xc208085fe0 sp=0xc208085f98
runtime.goexit()
	/private/tmp/go20170301-19561-2mto9i/go/gobootstrap/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208085fe8 sp=0xc208085fe0
go tool dist: FAILED: /private/tmp/go20170301-19561-2mto9i/go/pkg/tool/darwin_amd64/compile -pack -o /var/folders/x8/yzlh6tgn345ff6twgww_by280000gn/T/go-tool-dist-437138657/_go_.a -p sync /private/tmp/go20170301-19561-2mto9i/go/src/sync/cond.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/mutex.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/once.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/pool.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/race0.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/runtime.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/rwmutex.go /private/tmp/go20170301-19561-2mto9i/go/src/sync/waitgroup.go: exit status 2

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:422:in `open'
	from /usr/local/Library/Homebrew/utils.rb:452:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:484:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:154:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'

**Comment by simingli** [comment]
go version go1.7.3 darwin/amd64

**Comment by aarzilli** [comment]
Based on your error message it seems like brew is trying to install go1.5 and failing (because go1.5 does not support 10.12). This problem has been observed in the past (see issue #3) and it was solved by some user by fixing problems in their brew install.
